apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--2048
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: 'https://github.com/letfn/katt-2048'
    path: base
    targetRevision: 0.0.1
  destination:
    name: mbpro
    namespace: katt-2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
