apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--cilium
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: 'https://github.com/amanibhavam/spiral-mbpro'
    path: cilium
    targetRevision: 0.0.1
  destination:
    name: mbpro
    namespace: cilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
