apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--kuma-zone
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: 'https://github.com/amanibhavam/spiral-mbpro'
    path: kuma-zone
    targetRevision: master
  destination:
    name: mbpro
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
